### ISSUE TITLE
Vuln: MD5 hashed passwords are not sufficient

### ISSUE THREAD

**Issue by dominusbelli** [HackRU/lcs#11]
https://wiki.python.org/moin/Md5Passwords#Security

MD5 is not secure enough, use bcrypt or similar instead. ALSO please remember to salt the passwords. In its current state, you aren't salting passwords at all.
```
email = event['email']
pass_ = event['password']
pass_ = hashlib.md5(pass_.encode('utf-8') ).hexdigest() 
```

**Comment by hemangandhi** [comment]
Note: considering using https://stackoverflow.com/questions/9559549/how-to-compare-plain-text-password-to-hashed-password-using-bcrypt

**Comment by hemangandhi** [comment]
See #35
