### ISSUE TITLE
Auto deployment from master branch to AWS

### ISSUE THREAD

**Issue by Kironb** [HackRU/lcs#113]
Seeing as this is likely possible, we should try and set up some sort of auto-deployment tool for master off of github into AWS. There may be some issues that we may have to resolve along the way such as the pickle.py file that we generate.

**Comment by mjrb** [comment]
The script to generate the pickle file requires you to pull up a browser and click on things so thats very hard to slove with ci unless you use different credentials. I think it may be posible to create some kind of gsuite service account
