### ISSUE TITLE
Bug: After 500 users, users cannot change passwords

### ISSUE THREAD

**Issue by dominusbelli** [HackRU/lcs#12]
In authorize.py, ln 214, in change_password function,
```
if len(list(tests.find({"role":{"hacker":True}}))) >= 500:
        return {"statusCode":403, "body":"Event capacity reached."}
```
I'm not sure how it makes sense for users to not be able to change passwords when there are 500 users or more. It doesn't sound like FAD.

**Comment by hemangandhi** [comment]
There's no longer a `change_password` function... this was a misunderstanding.

Won't happen with feature branches.
