### ISSUE TITLE
Returns stats for a hackathon

### ISSUE THREAD

**Issue by ethxng** [HackRU/lcs#175]
In this issue, write an endpoint that returns the number of people based on their current registration status, such as the number of people who are currently unregistered, registered, confirmed to come, etc. Only "directors" are allowed to access this endpoint. Every other role who signed in would be given a 403 HTTP status code.

**Comment by sudo-CompSciGod** [comment]
https://www.geeksforgeeks.org/mongodb-countdocuments-method/

**Comment by sudo-CompSciGod** [comment]
Every status count except for unregistered
