### ISSUE TITLE
LCS login responses

### ISSUE THREAD

**Issue by mjrb** [HackRU/lcs#33]
Steps to reproduce:
`curl -X POST https://<LCS URL>/mlhtest/authorize -H "Content-Type: application/json" --data '{"email":"<VALID EMAIL>","password":"<INCORRECT PASS>"}' `
Actual behavior:
the error response is "invalid email,hash combo"
Expected behavior:
as implied by lcs [documentation](https://github.com/HackRU/lcs/wiki/LCS-API-Endpoints) if you give lcs a valid user with the wrong password it should return "wrong password" as the error.

related question:
the documentation also says that lcs could potentially give the error "Please use MLH to login". will this cause issues for user's returning to the hackathon who previously used mlh accounts to login? will they have to re-register? should we drop all of the pre-exisitng mlh accounts before sign up to avoid issues?

**Comment by hemangandhi** [comment]
We're dropping all users in a week. Then, yes, MLH stuff will be in the code, but not reachable by a frontend. For users, it won't matter - they'll never know what was.

**Comment by hemangandhi** [comment]
Updated docs.
