### ISSUE TITLE
Travel Reimbursement Estimates

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/lcs#42]
We need a means to update travel reimbursement information with estimates.

The current formula is as follows:
- If car: 0.12 * number of miles
- If bus: use wanderu to estimate reimbursement
- If train: use amtrak to estimate reimbursement
- Else (basically plane): $60 cap will probably hit

If the amount is above $60, just drop it to $60.

**Comment by hemangandhi** [comment]
See https://github.com/HackRU/handbook/pull/74

**Comment by mjrb** [comment]
Basically this we be a stream type service that responds to user creation / edit events and adds and calculates a hackers estimated reimbursement in lcs?
