### ISSUE TITLE
Move Camelot to own repo

### ISSUE THREAD

**Issue by QasimAbbas** [HackRU/lcs#46]
Would you be a able to move Camelot to its own repo and archive since it doesn’t have anything to do with lcs/is a separate stand alone project?

**Comment by hemangandhi** [comment]
Actually, do you want it before camelot and frontend split or after? Before would be more consistent, but only accurate up to Spring 2017. Fall 2017 was camelot + frontend split repos.

**Comment by QasimAbbas** [comment]
Whichever would be more consice, before the split then.

**Comment by hemangandhi** [comment]
Yote: https://github.com/HackRU/Camelot
