### ISSUE TITLE
google calendar api issue?

### ISSUE THREAD

**Issue by mjrb** [HackRU/lcs#57]
`curl https://m7cwj1fy7c.execute-api.us-west-2.amazonaws.com/mlhtest/dayof-events`
returns
`{"statusCode": 400, "body": "Unable to get events.", "headers": {"Access-Control-Allow-Origin": ["*"], "Access-Control-Allow-Headers": ["Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"], "Access-Control-Allow-Credentials": [true]}}`
did the calendar api credentials change or something?
we need this to finish the app

**Comment by hemangandhi** [comment]
There were no events.
