### ISSUE TITLE
Fix Slack Endpoint: Don't Use Workspace Tokens

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/lcs#61]
The poor slack documentation has declared that the workspace tokens we're using are going to die as of October. https://api.slack.com/docs/working-with-workspace-tokens

We need to find a free way to just read the messages on a channel for the slack endpoint.

**Comment by mjrb** [comment]
i used something other than a workspace token i think (it started with xoxp) so this might be fine

**Comment by mjrb** [comment]
this will be reopened if issues occur
