### ISSUE TITLE
QR Matching

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/lcs#63]
Match QRs from authentication to day-of QRs and handle all the day-of event updates through a separate endpoint.

May be use the misc bucket to validate the events.

**Comment by mjrb** [comment]
im moving event updates into a separate issue

**Comment by mjrb** [comment]
take in authEmail and token of person registering the hacker, the email of the hacker being registered, and the value of the badge being linked. then find the user in the databse and $push it to the array of linked qrs

**Comment by mjrb** [comment]
fixed by #80
