### ISSUE TITLE
day of event endpoint

### ISSUE THREAD

**Issue by mjrb** [HackRU/lcs#64]
handle all the day-of event updates through a separate endpoint.

May be use the misc bucket to validate the events.

**Comment by hemangandhi** [comment]
See #63 also

**Comment by mjrb** [comment]
this enpoint should take `{auth_email, token, qr}` as input and qr can be a qr linked to an account, or just the email. it should likely use existing code from #63

**Comment by mjrb** [comment]
fixed by #79 and #80
