### ISSUE TITLE
remove qr endpoint

### ISSUE THREAD

**Issue by mjrb** [HackRU/lcs#67]
its pretty easy for clients to grab a lib and generate a qr code themselves so this isn't strictly needed.
- [x] remove in source
- [x] remove in api gateway
- [x] remove in lambda
- ~~redeploy~~

**Comment by hemangandhi** [comment]
You don't need to redeploy unless I don't understand

**Comment by mjrb** [comment]
@hemangandhi I dont see any of the qr dependencies in `requirements.txt`. also what do you think about `qr_script.py` and `qr_script.sh`. are they usefull/shoud be kept around? or are they defunct because of the qr printer repo
