### ISSUE TITLE
Travel Reimbusement Amendments

### ISSUE THREAD

**Issue by thekabistro** [HackRU/lcs#69]
On the backend: 

We will now just display an amount based on the mileage.  If they've traveled x miles, then they get up to x amount.   This is for car mileage only. 

Miles (round trip) | Reimbursed Up To (Round Trip)
-- | --
0~49 | 0
50~100 | Up to 20
101 ~ 200 | Up to 40
201+ | Up to 59.99

For trains & buses --> $59.99 for everyone....

~~The "budget limiter" that scales down all reimbursements to not exceed a $1,500 budget limit, needs to be available.  We'll see if we use it based on applications....~~ (update, directors meeting 9/23, this is not needed)

the budget limter component from the old code is going to be removed. now if its train or bus it will just assign "up to" $59.99 and if they are coming by car, it will use google maps to find the distance and then assign whatever amount based on the above table

Otherwise, N/A

**Comment by mjrb** [comment]
@RidhwaanDev the issue was just updated

**Comment by mjrb** [comment]
fixed by #83
