### ISSUE TITLE
use json web tokens instead of uuids for login token and magic links

### ISSUE THREAD

**Issue by mjrb** [HackRU/lcs#76]
this allows us to encode whatever extra meta data we want like email and expiration. this reduces the amount of information clients hand to lcs, and gives clients more info on login. it also allows other backends to verify that a token is valid since jwt's can be public key signed.

in the case of magic links this can also let us pass the email to the client.

**Comment by RidhwaanDev** [comment]
This is mine now

**Comment by mjrb** [comment]
Lol you can just assign yourself to the issue if you want

**Comment by mjrb** [comment]
we can actually just do the login token part, the email part will be fixed by something else
